//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lung_Cancer_Detection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Desece
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Desece()
        {
            this.Results = new HashSet<Result>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<bool> IS_Deleted { get; set; }
        public string ImageLink { get; set; }
    
        public virtual Degrees_Of_Deseess Degrees_Of_Deseess { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Result> Results { get; set; }
    }
}
