//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lung_Cancer_Detection.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Canser_ProjectEntities : DbContext
    {
        public Canser_ProjectEntities()
            : base("name=Canser_ProjectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customar> Customars { get; set; }
        public virtual DbSet<Degrees_Of_Deseess> Degrees_Of_Deseess { get; set; }
        public virtual DbSet<Desece> Deseces { get; set; }
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<Persent> Persents { get; set; }
        public virtual DbSet<Test_Result> Test_Result { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Result> Results { get; set; }
    }
}
